mrphlip/lrrbot

lrrbot/__init__.py

This should stop `highlights.py` from unlinking the socket.

Delay the creation of the RPC socket

---

common/config.py
lrrbot/__init__.py
lrrbot/chatlog.py
requirements.txt
wwwsql/log.tbl

* Up IRC library version to include handling for IRCv3 tags
* Send CAP REQ messages on connect
* Get message metadata from IRCv3 tags instead of from "jtv" user
* NB: still getting notifications from "twitchnotify" user, that doesn't seem to have changed
* Update chatlog to use the new way of getting the emotes
* NB: still using the old way of generating the emotes for *outgoing* messages

Twitch chat protocol upgrades

---

common/config.py
common/utils.py
lrrbot/__init__.py
lrrbot/asyncreactor.py
lrrbot/chatlog.py
lrrbot/commands/card.py
lrrbot/commands/explain.py
lrrbot/commands/game.py
lrrbot/commands/highlights.py
lrrbot/commands/misc.py
lrrbot/commands/quote.py
lrrbot/commands/show.py
lrrbot/commands/static.py
lrrbot/commands/stats.py
lrrbot/commands/strawpoll.py
lrrbot/googlecalendar.py
lrrbot/serverevents.py
lrrbot/twitch.py
lrrbot/twitchsubs.py
lrrbot/whisper.py
rebuild_chat_logs.py
requirements.txt
start_bot.py
www/archive.py
www/static/style.css
www/templates/help.html

Bunch of changes for Twitch whispers:
* Separate class that handles connection to the group chat servers and sends/receives whispers. Is mostly decoupled from the main bot, so in theory it can be replaced if the mechanism changes. As far as most of the bot's concerned, it's just sending and receiving private messages in the normal IRC manner.
* Users can now send commands via whisper, and get responses via whisper. For some commands this is disabled (specifically ones that modify bot state, like `!death`), though mods can use any command (but I'd prefer you don't). Doing so also avoids the anti-spam throttles.
* Commands that used to be throttled silently will now send notifications via whisper. Commands that used to be throttled publicly (eg `!death`) still will be.
* New command …

Handle Twitch whispers

---

common/utils.py
lrrbot/commands/__init__.py
lrrbot/commands/live.py
lrrbot/main.py
lrrbot/twitch.py

New commands to replace the shady link to leg_bot's decaying carcass.
* `!live`: Post the currenly live fanstreamers.
* `!live register`: Register your channel as a fanstreamer channel.
* `!live register CHANNEL`: Register CHANNEL as a fanstreamer channel.
Once a day `!live` checks for new channels in the calendar.
List of channels leg_bot was checking:
```json
[
"only_scrubs_skip_leg_day",
"rebelliousuno",
"cantwearhats",
"caffeinatedlemur",
"durugai",
"rucdoc",
"vmkid",
"dix",
"admiralmemo",
"mowdownjoe",
"antitonic",
"mastercheese",
"polluxprocyon",
"hpbraincase",
"i_am_clockwork",
"rerout343",
"boofinka",
"rednightmare7",
"lambmower",
"reilaoda",
"themoosetetrino",
"selenes92",
"ranneko",
"senstaku",
"navarran",
"erockhiphop",
"uknit",
"darkmorford",
"mister_blue_sky",
"tstodden", …
```

!live, !live register, !live CHANNEL

---

lrrbot.service
lrrbot/main.py
lrrbot/systemd.py
lrrbot/whisper.py

`botscreen{,.sh}` is gone:
* `systemctl --user start lrrbot` to start the bot.
* `systemctl --user restart lrrbot` to restart the bot.
* `systemctl --user stop lrrbot` to stop the bot.
* `systemctl --user status lrrbot` to see the status and the last couple log entries.
I've set it up so to successfully start the bot it must connect to the main IRC servers and to the group chat servers (if the whispers are enabled of course). Because Twitch this can sometimes fail and you need to try again. Also if the bot gets stuck for more than two minutes it will be automatically restarted.

systemd support

---

common/http.py
common/utils.py
lrrbot/chatlog.py
lrrbot/main.py
www/archive.py
www/login.py

There are still two bare `except`s in `lrrbot.chatlog.do_rebuild_all` and  `common.utils.log_errors`. Those do some cleanup actions and immediately re-`raise` them.

Don't catch `BaseException`s.

---

alembic/versions/77dc71b483ed_users_foreign_keys.py
alembic/versions/a6854cd2e5f1_users.py
alembic/versions/d88d63c07199_.py
common/config.py
common/twitch.py
highlights.py
lrrbot/commands/game.py
lrrbot/commands/highlights.py
lrrbot/commands/live.py
lrrbot/commands/misc.py
lrrbot/commands/show.py
lrrbot/main.py
lrrbot/serverevents.py
lrrbot/twitchsubs.py
lrrbot/whisper.py
requirements.txt
www/api.py
www/botinteract.py
www/commands.py
www/history.py
www/login.py
www/notifications.py
www/spam.py
www/templates/help.html
www/templates/master.html
www/votes.py

Replaces `"autostatus"`, `"mods"`, `"subs"` and `"twitch_oauth"` keys in `data.json`. The migration script fetches user IDs from Twitch for 3k users so it can take a while. Uses Postgres 9.5 `INSERT ... ON CONFLICT ... DO UPDATE ...` syntax.

Add `users` table

---

lrrbot/command_parser.py
lrrbot/commands/explain.py
lrrbot/commands/misc.py
lrrbot/commands/static.py
lrrbot/linkspam.py
lrrbot/main.py
lrrbot/rpc.py
lrrbot/spam.py
lrrbot/twitchsubs.py
start_bot.py

I used `irc`'s event handlers to link the code back together.
`'privmsg'` and `'pubmsg'` handers:
Priority | Handler
-------- | -------
0 | add wrapper to `Connection.privmsg` 
1 | check message tags
2 | add message to chat log
20 | spam filter
21 | link spam filter
90 | notifications
99 | commands
Priorities 0-19 would deal with the IRC protocol, 20-89 would be filters and 90-99 would process the messages.

Move code out of `lrrbot.main`

---

lrrbot/emote_spam.py
lrrbot/main.py

Allows up to 8 subscriber emotes from any channel (and possibly Turbo emotes?) or up to 5 global emotes. Uses cost system so that it behaves reasonably when mixing emotes.

Detect emote spam

---

alembic/versions/affc03cb46f5_game_data.py
common/game_data.py
common/utils.py
lrrbot/commands/game.py
lrrbot/commands/misc.py
lrrbot/commands/quote.py
lrrbot/commands/show.py
lrrbot/commands/stats.py
lrrbot/main.py
lrrbot/rpc.py
lrrbot/storage.py
www/api.py
www/botinteract.py
www/login.py
www/quotes.py
www/static/style.css
www/stats.py
www/templates/stats.html
www/votes.py

There are a lot of things wrong with this code: no query optimisation work has been done: the queries do multiple passes over the same data and there are no indexes, there are no management interfaces and tables have awkward names. Since this is a huge changeset I want to merge this before it bitrots too heavily.
I changed `!complete` and `!game complete` to no longer be mod-only.
Added the option to disable stats. Disabled stats can't be incremented with `!<stat>` and are de-emphasised or in some cases hidden on the website. The migration script automatically disables deaths, paves and tilts on A Swiftly Tilting Cameron.
For #89. For #83. Closes #184.

Move game data to database

---

LICENSE
README.md

[License text](https://www.apache.org/licenses/LICENSE-2.0). TL;DR: MIT license with explicit patent grant.
To do this, I need explicit approval from each contributor of copyrightable work. I think this is everyone who has contributed to non-MIT licensed modules:
If you agree with relicensing, reply with something like 'I license past and future contributions under the Apache-2.0 license'. If you're a contributor you can also check the checkbox next to your name.

Relicense under Apache-2.0

---

www/static/style.css

Before:
After:
Everything else looks the same to me.

Switch CSS box model

---

.gitignore
common/config.py
common/utils.py
logging.conf
start_bot.py
webserver.py

Set up rolling log files and a separate temporary file for debug logging, so that the debug logs are there if we need to look at them, but aren't kept forever taking up space.
I'm thinking of when I tried setting the bot to debug mode recently to look into it constantly reconnecting... but that required restarting the bot, which cleared the issue... would have been nice to have it doing full debug logging already... but we don't want to keep debug logs forever, that's just too much stuff we don't care about.
Note: I've checked that the logging conf loads properly, but I haven't tested the whole bot with this... I still need to update my comp to Python 3.5

Add a proper logging conf file

---

alembic/versions/89c5cb66426d_add_bits_to_storm.py
common/storm.py
lrrbot/chatlog.py
lrrbot/commands/misc.py
lrrbot/main.py
lrrbot/twitchcheer.py
www/api.py
www/notifications.py
www/static/archive.css
www/static/notifications.js
www/static/style.css
www/templates/notifications.html

Closes #235 
Note for @paul-lrr:
The messages for these will come down the same as all the other event notifications, with the event type `twitch-cheer`. The data block looks like:
```json
{
"name": "MrPhlip",
"message": "Testing out this cheer thing... cheer50",
"bits": 50,
"count": 123456,
"level": "gray"
}
```
Where `bits` is the number of bits in this message;  `count` is the running total for the day. `level` is one of: gray, purple, green, blue, or red.

Cheer tracking

---

.gitignore
README.md
common/config.py
lrrbot/main.py
requirements.txt
www/login.py

Breaking changes:
* The default IRC server is now `irc.chat.twitch.tv:6697` over TLS.
* Redirect URI for Twitch authentication is no longer hardcoded.

Setup instructions

---

README.md

Various requirements fail to install without `build-essential` on Ubuntu 16.10.

Add missing dependency to setup instructions

---

alembic/versions/0dec7733925d_rename_highlights_user.py
alembic/versions/0e33b11b0930_drop_patreon_users_last_announce_month.py
alembic/versions/286bd48821dd_rename_users_patreon_user.py
alembic/versions/7c9bbf3a039a_game_stats_stat_id.py
common/patreon.py
highlights.py
lrrbot/commands/highlights.py
www/login.py
www/patreon.py
www/templates/patreon.html

* Update the foreign key on `game_stats.stat_id` to reference `stats.id` instead of `shows.id`. Closes #250.
* Rename `highlights.user` to `highlights.user_id`.
* Rename `users.pateron_user` to `users.patreon_user_id`.
* Drop `patreon_users.last_announce_month`. It was never used and never will.

Fix database schema inconsistencies

---

README.md

The Google Calendar integration uses an API key, and not OAuth credentials, to authenticate with Google's servers. This removes a reference to OAuth from the corresponding line of the README.

Update README.md: Google Calendar key is not OAuth

---

common/config.py
eris/__init__.py
eris/channel_reaper.py
eris/commands/__init__.py
eris/commands/live.py
eris/commands/voice.py
start_eris.py

New command: `!voice CHANNEL`. It creates a new voice channel named '[TEMP] CHANNEL'.
Once a minute all voice channels that start with `[TEMP] `, are empty and are older than fifteen minutes are deleted.

discord: temporary voice channels

---

.editorconfig
common/config.py
common/rpc.py
eris/__init__.py
eris/announcements.py
eris/autotopic.py
eris/rpc.py
lrrbot/main.py
lrrbot/stream_status.py
lrrbot/video_playback.py
requirements-direct.txt
requirements.txt
start_eris.py

It polls the stream endpoint but also uses the undocumented and unsupported `video-playback` PubSub topic to flush the caches early. This should mean that if `video-playback` disappears the rest should still continue to work. Because we can't rely on `video-playback` the notifications are delayed by several minutes due to Twitch's internal caches.
New events in the notification stream:
```
id:46829
event:stream-up
data:{"time": "2017-06-16T16:21:54.365842+00:00"}
id:46830
event:stream-down
data:{"time": "2017-06-16T16:28:23.085681+00:00"}
```
LRRbot will also post a notification in Discord.

Stream start and end notifications

---

common/cardname.py
eventserver.py
lrrbot/cardviewer.py
lrrbot/main.py
lrrbot/rpc.py
webserver.py
www/api_v2.py
www/notifications.py
www/static/notifications.js
www/templates/api_v2_docs.html
www/templates/notifications.html

v1 still exists and will be removed when LRR stops using it.
Removed in v2:
* `GET /next`
* `GET /game`
* `GET /show`
Different in v2:
* `GET /show/<name>` is now `PUT /show`.
* `GET /disconnect` is now `POST /disconnect`.
* `GET /tweet` no longer requires a moderator.
* The notification events endpoint (`/notifications/events`) is now part of the API. For now a redirect is in place that will be removed with the v1 API.
New in v2:
* `POST /cardviewer`: replacement for PubNub.
Documentation: https://lrrbot.mrphlip.com/api/v2/
cc: @paul-lrr

API v2: remove unused endpoints and add /api/v2/cardviewer

---

lrrbot/stream_status.py

The stream-status processing could get doubled if `reschedule` was
called while `check_stream` was running (eg if it was called twice in
quick succession). Then if `check_stream` runs while another instance of
`check_stream` was `await`ing sending a message (between checking the
stream status and updating `was_live`) then both of them could send the
gone-live announcement to Discord. And they'd both schedule another
instance so it will keep happening.
Add extra handling so only one `check_stream` should ever be scheduled,
and make sure that even if `check_stream` is called twice at once, we
update `was_live` before `await`ing so that only one message should be
sent.

Fix doubled stream go-live announcements

---

common/state.py
lrrbot/commands/strawpoll.py
lrrbot/main.py

Uses the [descriptor protocol](https://docs.python.org/3/howto/descriptor.html) to convert field accesses into database queries.
My only concern is that this is too magical because it masquerades potentially expensive database queries as cheap field accesses. But `SELECT value FROM state WHERE key = $0` should be fast and the database is on the same node. A way to lessen the impact of that would be to add a simple write-through cache but I'm not completely sure it's necessary.
`spammers` should be exempt because spam bots tend to only get hit once.
Closes #153.

Store the bot state in the database

---

README.md

Ubuntu 16.10 EOL'ed over a year ago, so the exact instructions are a bit difficult to follow.  Version numbers taken from discussion in Discord, but I didn't test against them before adding the information.

Add more details on dependencies to README.md

---

alembic/versions/dd3efe83691d_drop_card_collector.py
alembic/versions/ee81e255ddc0_drop_cards_lastprinted.py
build_carddb_keyforge.py
build_carddb_mtg.py
common/http.py
lrrbot/commands/card.py

For MTG every database query we do for every card adds about 12 seconds to the script's runtime.
* Process cards in a reverse chronological order
* Keep track of what cards have been processed already
* Drop collector numbers
* [MTG] Deduplicate multiverse IDs
* [MTG] Keep track of processed multiverse IDs because Throne of Eldraine is weird and has some cards twice. Something something `"frameEffects": ["showcase"]`.
* [MTG] use the best compression format that is supported by Python's standard library. Probably doesn't matter much but the XZ is half the size of the ZIP (21.7 MiB vs 43.4 MiB).
* [Keyforge] Swap out `common.http.request` for `requests`.
* [Keyforge] Retry throttled requests.
`build_carddb_mtg.py` now takes 23 seconds to run instead of a minute and 47 seconds. I didn't …

Speed up MTGJSON processing 12 times

---

Pipfile
Pipfile.lock
common/spam.py
lrrbot/linkspam.py
lrrbot/spam.py
www/history.py
www/server.py
www/spam.py
www/static/spam.js
www/templates/historyshow.html
www/templates/spam.html

Adds spam filter pattern types:
* Text: case sensitive string match
* Confusables: string match but consider the Unicode confusables table. Uses the `confusables` package.
* Regular expression: the same as before
Since link spam detection uses most of the same infrastructure it gets these changes as well.
Also the webserver initialisation had bitrotted and the debug server wouldn't start.

Add plaintext and confusable spam filter pattern types

---

build_carddb_lorcana.py
build_carddb_mtg.py
common/card.py
common/http.py
lrrbot/commands/card.py
www/api_v2.py
www/templates/api_v2_docs.html

This adds a build script to add Lorcana cards to the cards database, in the same style as 'build_carddb_mtg'.
It also adds the '!lorcana' command to look up the cards, again in the same way as the other card lookups work.
It doesn't hook the Lorcana data up to the card reader code, because I don't know how that works and didn't want to make too big a pull request.

Add Lorcana card lookup

---

build_carddb_lorcana.py

This is needed because special Enchanted-rarity cards have the same name as their non-Enchanted-rarity equivalents

Don't store duplicate Lorcana cards
