mrphlip/lrrbot

- www/archive.py
- www/templates/archive_watch.html
> Fix embedded player

- requirements.txt
- webserver.py
- www/commands.py
- www/notifications.py
- www/server.py
- www/spam.py
- www/static/commands.js
- www/static/notifications.js
- www/static/spam.js
- www/static/votes.js
- www/templates/commands.html
- www/templates/spam.html
- www/templates/votes.html
- www/votes.py
> Add CSRF protection

- common/utils.py
This morning the bot had been waiting for Twitch to reply for 12 hours.
> http_request: connection timeout

- lrrbot/chatlog.py
> chatlog: Fall back to `/chat/emoticon_images`.

- lrrbot/commands/__init__.py
- lrrbot/commands/quote.py
- webserver.py
- www/quotes.py
- www/templates/master.html
- www/templates/quotes.html
- wwwsql/quotes.tbl
Differences with Pump19:
* No quote rating. It isn't strictly necessary and if needed can be added later.
* Awful web interface. I can't HTML or CSS.
CC: @TwistedPear-AT
Closes #40.
> Use Pump19 quote code

- lrrbot/commands/quote.py
> Change `!quote` and `!findquote` to be sub-only.

- lrrbot/googlecalendar.py
> googlecalendar: Include location when coalescing events

- lrrbot/commands/live.py
> !live: Ignore the channel LRRbot is on

- common/utils.py
`res.text()` technically does that internally but the documentation
states to not rely on that behavior.
Should fix the bug when HTTP requests randomly start failing.
> http_request_coro: release connections to pool

- common/utils.py
Maybe we should update to Python 3.5...
> utils.http_request_coro: Manage resources manually like it's 1972.

- common/utils.py
> Workaround for #130: Do GET requests instead of HEAD.

- lrrbot/whisper.py
> Ignore `ServerNotConnectedError`

- www/stats.py
- www/templates/stats.html
Showing all games would freeze up single-threaded web browsers like Firefox.
> www.stats: On the 'All' page show stats per show.

- common/config.py
- lrrbot/cardviewer.py
> Prepare for pre-prerelease: parse URL

- common/space.py
- lrrbot/chatlog.py
- lrrbot/commands/live.py
- lrrbot/commands/strawpoll.py
- lrrbot/googlecalendar.py
- www/server.py
> add `common.space.SPACE` to the end of every URL

- lrrbot/chatlog.py
> Add `rel="noopener nofollow"` to chat links.

- lrrbot/commands/misc.py
- lrrbot/main.py
> !viewers: use IRC to get NAMES list, lower throttle timeout

- common/config.py
- common/slack.py
- lrrbot/linkspam.py
- lrrbot/main.py
Because a) LRRbot is no longer sending the 'spam detected' messages to the chat and b) is shadowbanned from sending whispers there is no way for other mods to know why LRRbot's spam filter was triggered. This will post a short message to the #moderator-things channel.
> Slack integration

- lrrbot/commands/explain.py
- lrrbot/commands/static.py
- lrrbot/decorators.py
> Send message status via whisper.

- lrrbot/join_filter.py
- lrrbot/main.py
- lrrbot/twitchsubs.py
> Filter JOINs

- lrrbot/commands/quote.py
Adds the ability to search for quotes by game or show name.
`!quote game Dark Souls` or `!quote show IDDQDerp`
Added as part of https://github.com/mrphlip/lrrbot/issues/165
> Add quote search by game or show name

- lrrbot/commands/game.py
> Fix `!game refresh`

- common/game_data.py
- common/postgres.py
- common/sqlalchemy_pg95_upsert.py
- lrrbot/commands/game.py
- lrrbot/commands/stats.py
- lrrbot/main.py
- www/login.py
- www/server.py
- www/votes.py
Based on https://bitbucket.org/robin900/sqlalchemy/branch/ticket_3529.
> Monkey patch SQLAlchemy to have UPSERT support

- alembic/versions/954c3c4caf32_.py
- alembic/versions/f2ecbd726b58_patreon.py
- common/config.py
- common/patreon.py
- lrrbot/commands/__init__.py
- lrrbot/commands/patreon.py
> Initial Patreon support and `!patreon` command.

- lrrbot/main.py
> Check for responses for PINGs.

- common/utils.py
- lrrbot/twitchsubs.py
> Rename `twitch-resubscription` counter

- common/twitch.py
- lrrbot/commands/misc.py
- lrrbot/main.py
- lrrbot/twitchfollows.py
Counter added to !storm as well.
Closes #199.
> Twitch followers

- lrrbot/googlecalendar.py
I've been thinking about it and there have been requests for it from chat. The description is limited to 200 code points although an adaptive limit could be implemented. Like `!live` if the message is longer than 450 code points some details are progressively removed.
> !next: display description from calendar

- common/pubsub.py
- common/slack.py
- lrrbot/chatlog.py
- lrrbot/main.py
- lrrbot/moderator_actions.py
- requirements.txt
LRRbot's Slack messages now have 300% more spam!
> Log all moderator actions to Slack

- lrrbot/moderator_actions.py
> Fail silently when the users table is empty.

- common/config.py
- eris.service
- eris/__init__.py
- eris/autotopic.py
- logging.conf
- requirements.txt
- start_eris.py
For #261.
I've also created the neccesary keys and IDs and the bot account.
> Discord: initial framework and autoupdating topic

- eris/autotopic.py
- eris/command_parser.py
- eris/commands/__init__.py
- eris/commands/live.py
- start_eris.py
Also adjust autotopic messages.
For #261.
> Discord: !live

- lrrbot/twitchsubs.py
There might be double subs today.
> twitchnotify is going to be/was removed today.

- common/googlecalendar.py
> Structured show descriptions

- common/twitch.py
- lrrbot/moderator_actions.py
The ["documentation"](https://discuss.dev.twitch.tv/t/allowing-others-aka-bots-to-use-twitchbot-reject/8508/2) is lies.
> Revert "Auto-approve messages rejected by Automod"

- alembic/env.py
- alembic/versions/77dc71b483ed_users_foreign_keys.py
- alembic/versions/a6854cd2e5f1_users.py
- alembic/versions/affc03cb46f5_game_data.py
- build_carddb.py
- common/http.py
- common/postgres.py
- common/twitch.py
- common/utils.py
- eris/commands/live.py
- eventserver.py
- find_clips.py
- highlights.py
- lrrbot/chatlog.py
- lrrbot/commands/live.py
- lrrbot/main.py
- lrrbot/moderator_actions.py
- lrrbot/twitchfollows.py
- start_eris.py
- www/archive.py
- www/clips.py
- www/login.py
- www/server.py
- www/templates/archive_video.html
- www/templates/clips_vidlist.html
> Convert Twitch API calls to version 5

- common/config.py
- eris.service
- requirements-direct.txt
- requirements.txt
- start_eris.py
> Use only Discord over Tor

- common/config.py
- eris.service
- requirements-direct.txt
- requirements.txt
- start_eris.py
Reverts mrphlip/lrrbot#342
Well, this didn't work.
> Revert "Use only Discord over Tor"

- eris/commands/__init__.py
- eris/commands/time.py
> eris: add !time

- common/config.py
- eris/commands/voice.py
Because discord.py continues to be toilets I'm making the request directly.
> eris: create temporary voice channels in the voice channel category

- lrrbot/twitchsubs.py
The gift subscriptions show up as normal subscriptions on the notification page.
@paul-lrr: `twitch-subscription` and `twitch-resubscription` events have an additional field named `"benefactor"` which is either the display name of the user gifting the subscription or `null`.
Closes #395.
> Sub gifting

- alembic/versions/643aab2ac6ed_add_team_battle_to_storm.py
- lrrbot/commands/misc.py
- lrrbot/twitchcheer.py
- www/api_v2.py
> Add #teambattle hashtag tracking for bits

- README.md
- alembic/versions/77dc71b483ed_users_foreign_keys.py
- alembic/versions/a6854cd2e5f1_users.py
- alembic/versions/affc03cb46f5_game_data.py
- common/config.py
- common/http.py
- common/twitch.py
- common/utils.py
- find_clips.py
- find_clips.service
- find_clips_slow.service
- find_clips_week.service
- lrrbot/chatlog.py
- lrrbot/commands/live.py
- lrrbot/commands/misc.py
- lrrbot/commands/show.py
- lrrbot/linkspam.py
- lrrbot/main.py
- lrrbot/moderator_actions.py
- lrrbot/twitchfollows.py
- lrrbot/twitchsubs.py
- www/archive.py
- www/clips.py
- www/login.py
- www/templates/api_v2_docs.html
- www/templates/archive_video.html
- www/templates/clips_external.html
- www/templates/clips_vidlist.html
- www/templates/login.html
https://dev.twitch.tv/docs/api/migration
https://dev.twitch.tv/docs/api/reference
> New twitch api

- build_carddb_lorcana.py
Location-type cards in Lorcana have some special numbers that are important to show.
This merge request adds those values to the output
> Add Lorcana Location-card details

- build_carddb_lorcana.py
Adapt to v2 dataformat changes of LorcanaJSON.
Also fix an issue when two cards with different cases exist.
> Update Lorcana carddb builder
